### ISSUE TITLE
Updates?

### ISSUE THREAD

**Issue by noelleleigh** [bahamas10/sombra#6]
Will you be adding updates about the [end of the amomentincrime.com countdown](https://www.reddit.com/r/Overwatch/comments/5860e8/list_of_only_new_things_that_popped_up_after/), and the [Dorado Sombra beeps](https://www.reddit.com/r/Overwatch/comments/58bimb/bastion_dorado_sombra_beeps/)?

**Comment by bahamas10** [comment]
already working on it now, thanks!
