### ISSUE TITLE
Lumerico Git

### ISSUE THREAD

**Issue by jakehamilton** [bahamas10/sombra#7]
Pretty new to ARG's in general, so not sure if this is real or just bait by someone else. But in seeing the latest I was wondering about the git repository mentioned.

In short, found this: https://github.com/lumerico?tab=overview&from=2016-10-19

Joined yesterday and created a single repository with an interesting description. However, again, not sure if it's someone messing around or real. Hopefully you guys can make some more sense of it.

**Comment by jakehamilton** [comment]
The linked repository still may be something, but looks like the repository for the lumerico.mx/president-bypass stuff was found: https://www.reddit.com/r/gamedetectives/comments/58cz9d/lumericomx_git_files/

**Comment by bahamas10** [comment]
Really interesting about the new github user... not sure what to make of that... but so far we have no reason to believe that is real (but I won't rule it out).

Also, I've added all of the president-bypass git stuff to the repo here, thanks!

**Comment by jakehamilton** [comment]
Agreed, great work so far!
